name: pagbank
description: Banco Digital

author:
  developer:
    name: Lucas Paz e Lucas Assis
    github: github.com/luscas
    site: lucaspaz.com
  designer:
    name: Lucas Assis
    instagram: instagram.com/lucasassis.design/
    site: uistart.com.br


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/2.0x/
  fonts:
    - family: Work Sans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700